### ISSUE TITLE
Logo Design: HologramShader

### ISSUE THREAD

**Issue by baranpirincal** [andydbc/HologramShader#2]
Hello!

 I'm a graphic designer and I like to support open source projects. I would like to design a logo for your project if you interested, I will be happy to work with you! :)

Best Regards

Baran Pirinçal

Graphic Designer

**Comment by andydbc** [comment]
Hello Baran,

Unfortunately, I will decline your proposal, this project was started as an experiment. It is not a true open source project.

Thanks, 
Andy
