### ISSUE TITLE
An asset in Unity AssetStore seems using codes from here.

### ISSUE THREAD

**Issue by chocobon** [andydbc/HologramShader#5]
An asset in Unity AssetStore below seems using codes from here. Please check.
https://assetstore.unity.com/packages/vfx/shaders/simple-hologram-shader-120065

**Comment by andydbc** [comment]
I already reported this asset to Unity.
Unfortunately, It's possible that this asset doesn't infringe the MIT licence.
He did it with a bunch of open source projects... It's disgusting but I can't do much.

**Comment by andydbc** [comment]
Package has been deprecated from the Asset Store.
